default_light:
  ### Fonts ###
  primary-font-family: "'Open Sans', 'Rubik', Roboto, sans-serif"
  paper-font-common-base_-_font-family: "var(--primary-font-family)"
  paper-font-common-code_-_font-family: "var(--primary-font-family)"
  paper-font-body_-_font-family: "var(--primary-font-family)"
  paper-font-subhead_-_font-family: "var(--primary-font-family)"
  paper-font-headline_-_font-family: "var(--primary-font-family)"
  paper-font-caption_-_font-family: "var(--primary-font-family)"
  paper-font-title_-_font-family: "var(--primary-font-family)"

  ha-card-border-radius: "0px"
  ha-card-header-color: "#757575"
  ha-card-box-shadow: "0 0 5px 0 rgba(43,43,43,0.1), 0 6px 6px -7px rgba(43,43,43,0.1)"
  ha-card-header-font-size: "18px"
  ha-card-header-font-family: "'Roboto', sans-serif"

  ### Main Interface Colors ###
  primary-color: "var(--mdc-theme-primary)"
  light-primary-color: "#c1c1c1"
  primary-background-color: "#f2f7fb"
  secondary-background-color: "#ffffff"
  divider-color: "#e7e7e7"
  paper-icon-button-active-color: "#061014"
  paper-icon-button-inactive-color: "#a1a1a1"
  paper-item-icon-color: "#212528"
  paper-item-icon-active-color: "#d0d1d1"
  ### Text ###
  primary-text-color: "#000000"
  secondary-text-color: "#757575"
  text-primary-color: "#ffffff"
  disabled-text-color: "#a1a1a1"
  ### Sidebar Menu ###
  sidebar-background-color: "#ffffff"
  sidebar-icon-color: "#3f5975"
  sidebar-text-color: "#000000"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#4099ff"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)
  ### States and Badges ###
  state-icon-color: "#606367"
  state-icon-active-color: "#4099ff"
  state-icon-unavailable-color: var(--disabled-text-color)
  ### Sliders ###
  paper-slider-knob-color: "#4099ff"
  paper-slider-knob-start-color: "#8eb8ff"
  paper-slider-pin-color: "#8eb8ff"
  paper-slider-active-color: "#8eb8ff"
  paper-slider-secondary-color: var(--light-primary-color)
  paper-slider-container-color: "#e7e7e7"
  ### Labels ###
  label-badge-background-color: "#252B36"
  label-badge-text-color: "#F1F1F1"
  label-badge-red: "#6C7B9B"
  ### Cards ###
  paper-card-background-color: "#ffffff"
  paper-listbox-background-color: "#ffffff"
  ### Toggles ###
  paper-toggle-button-checked-button-color: "#4099ff"
  paper-toggle-button-checked-bar-color: "#4099ff"
  paper-toggle-button-unchecked-button-color: "#4099ff"
  paper-toggle-button-unchecked-bar-color: "#c1c1c1"

  ### Dialog ###
  paper-dialog-background-color: "#ffffff"

  ### Table row ###
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)

  iron-overlay-backdrop-background-color: "#ffffff"
  mdc-theme-primary: "#03a9f4"
