- platform: manual
  name: Home Alarm
  code: !secret alarm_code
  arming_time: 30
  delay_time: 20
  trigger_time: 60
  disarm_after_trigger: true
  disarmed:
    trigger_time: 0
  armed_home:
    arming_time: 0
    delay_time: 0
