- id: '1640227090994'
  alias: Record camera on doorbell ring
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: abe2aa0a7ac54e7688e9bfaa37c7d025
    entity_id: binary_sensor.front_door_ding
    domain: binary_sensor
  condition: []
  action:
  - service: camera.record
    target:
      entity_id: camera.entrance
    data:
      duration: 30
      filename: /tmp/camera_entrance_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4
  mode: single
- id: '1640320206573'
  alias: Turn off the boiler at a specific time
  description: ''
  trigger:
  - platform: time
    at: input_datetime.boiler_end_time
  - platform: state
    entity_id: switch.boiler
    for:
      hours: 8
      minutes: 0
      seconds: 0
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.boiler
    state: 'on'
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.boiler
  - service: notify.notify
    data:
      message: A caldeira foi desligada.
      title: Caldeira
  mode: single
- id: '1640844948467'
  alias: Notify when the garage is open
  description: ''
  trigger:
  - platform: state
    entity_id: cover.garage_door
    to: open
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      title: Garagem
      message: A garagem está aberta há algum tempo. Quer fechá-la?
      data:
        actions:
        - action: CLOSE_GARAGE
          title: Fechar a Garagem
          destructive: true
  mode: restart
- id: '1640845153052'
  alias: Close the garage on notification action
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: CLOSE_GARAGE
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.garage_door
  mode: single
- id: '1640845767668'
  alias: Turn on the entrance lights on gate open
  description: ''
  trigger:
  - platform: state
    entity_id: lock.entrance_small_gate
    to: unlocked
  - platform: state
    entity_id: cover.garage_door
    to: open
  condition:
  - condition: state
    entity_id: light.entrance
    state: 'off'
  - condition: time
    after: '18:00'
  action:
  - service: light.turn_on
    target:
      entity_id: light.entrance
    data: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    target:
      entity_id: light.entrance
  mode: single
- id: '1641268171828'
  alias: Set the default theme at start up
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: frontend.set_theme
    data:
      name: Google Dark Theme
  mode: single
- id: '1642368840598'
  alias: Trigger the alarm when movement is detected
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.body_sensors
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.home_alarm
  mode: single
- id: '1642368957917'
  alias: Flash the lights when alarm is triggerd
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: before_alarm
      snapshot_entities:
      - light.living_room
  - service: light.turn_on
    data:
      entity_id: light.living_room
      effect: Alarm
      brightness: 255
  - wait_for_trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
    continue_on_timeout: true
    timeout: '300000'
  - service: light.turn_on
    data:
      entity_id: light.living_room
      effect: Stop
  - service: scene.turn_on
    data:
      entity_id: scene.before_alarm
  mode: single
- id: '1642369308931'
  alias: Notify when alarm is triggered
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: triggered
  condition: []
  action:
  - service: notify.notify
    data:
      title: Alarme disparado
      message: O alarme disparou às {{ states('sensor.time') }}!
  - wait_for_trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: disarmed
    timeout: '300000'
  - service: notify.notify
    data:
      title: Alarme desarmado
      message: O alarme foi desarmado às {{ states('sensor.time') }}
  mode: single
- id: '1642369789541'
  alias: Notify when doorbell rings
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.front_door_ding
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    entity_id: camera.entrance
    data:
      filename: /tmp/camera_entrance_snapshot.jpg
  - service: notify.notify
    data:
      title: Campaínha
      message: Alguém está a tocar à campaínha!
      data:
        entity_id: camera.entrance
        image: /tmp/camera_entrance_snapshot.jpg
        actions:
        - action: OPEN_SMALL_GATE
          title: Abrir a Porta
          destructive: true
  mode: single
- id: '1642369835158'
  alias: Open small gate on notification action
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: OPEN_SMALL_GATE
  condition: []
  action:
  - service: lock.open
    target:
      entity_id: lock.entrance_small_gate
  mode: single
