# Main configuration
homeassistant:
  name: "Home Hub"
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  auth_mfa_modules:
    - type: totp
  whitelist_external_dirs:
    - /tmp
    - /media
  external_url: "https://home.plourenco.com"
  internal_url: "https://home.plourenco.com"
  media_dirs:
    local: /media

system_health:
logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    pyhap: debug

lovelace:
  mode: storage

input_select:
input_datetime:
input_boolean:
input_number:
input_text:

# HTTP setup
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.21.0.0/16

# MQTT broker
mqtt:
  broker: mqtt
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

# Frontend themes & extras
frontend:
  themes: !include_dir_merge_named themes 

# Integrations
sun:
yeelight:
  devices: !include yeelight.yaml
ring:
  username: !secret ring_username
  password: !secret ring_password
webostv:
  host: 192.168.1.87
  name: Living Room TV

# Streaming
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
stream:

# iOS setup
ios:
homekit: !include_dir_merge_list homekit/

# Text to speech
tts:
  - platform: google_translate

# Log recorder
logbook:
  exclude:
    domains:
      - weather
      - sensor
      - script
history:

recorder:
  auto_purge: true
  purge_keep_days: 14
  exclude:
    domains:
      - automation
      - updater
      - script
    entities:
      - sun.sun

# Mobile app integration
mobile_app:
notify: !include notify.yaml
media_source:

# Devices
group: !include groups.yaml
automation: !include automations.yaml
automation files: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
sensor: !include_dir_merge_list sensors/
light: !include_dir_merge_list lights/
binary_sensor: !include_dir_merge_list binary_sensors/
cover: !include_dir_merge_list covers/
switch: !include_dir_merge_list switches/
camera: !include_dir_merge_list cameras/
scene: !include_dir_merge_list scenes/
media_player: !include_dir_merge_list media_players/
lock: !include_dir_merge_list locks/
climate: !include_dir_merge_list climate/

# Device discovery
discovery:

# Alarm
alarm_control_panel: !include alarm.yaml
