# Names
light.living_room_lights:
  friendly_name: Living Room Lights
cover.living_room_shutter_left:
  friendly_name: Living Room Shutter (Left)
cover.living_room_shutter_right:
  friendly_name: Living Room Shutter (Right)
light.living_room_lights:
  friendly_name: Living Room Lights
light.living_room_lights_left_1:
  friendly_name: Living Room Lights (Left)
light.living_room_lights_right_1:
  friendly_name: Living Room Lights (Right)
light.office_lights:
  friendly_name: Office Lights
alarm_control_panel.home_alarm:
  friendly_name: Alarm
media_player.living_room_tv:
  friendly_name: Living Room TV
  device_class: tv

# Classes & state
cover.garage_gate:
  friendly_name: Garage Gate
  assumed_state: false
  device_class: garage
cover.outside_gate:
  friendly_name: Outside Gate
  assumed_state: false
  device_class: garage

# Hidden
switch.living_room_tv_toggle:
  hidden: true
switch.garage_gate:
  hidden: true
switch.outside_gate:
  hidden: true
