auto_start: true
safe_mode: true
advertise_ip: !secret base_ip
filter:
  include_entities:
    - cover.outside_gate
    - cover.garage_gate
    - cover.living_room_shutter_left
    - cover.living_room_shutter_right
    - alarm_control_panel.home_alarm
    - light.living_room_lights
    - light.living_room_lights_left_1
    - light.living_room_lights_right_1
    - light.office_lights
    - media_player.living_room_tv
entity_config:
  media_player.living_room_tv:
    feature_list:
      - feature: on_off
      - feature: toggle_mute
