- platform: "mqtt"
  name: "body_sensor_occupancy_1"
  state_topic: "zigbee/tele/SENSOR"
  payload_on: "1"
  payload_off: "0"
  value_template: >
    {% if value_json.ZigbeeReceived['0x31B1'] is defined %}
      {{ value_json.ZigbeeReceived['0x31B1'].Occupancy }}
    {% else %}
      {{ states('sensor.body_sensor_occupancy_1') }}
    {% endif %}
