- platform: "mqtt"
  name: "kitchen_body_sensor"
  state_topic: "zigbee/tele/SENSOR"
  payload_on: "1"
  payload_off: "0"
  value_template: >
    {% if value_json.ZbReceived['kitchen_body_sensor'] is defined %}
      {{ value_json.ZbReceived['kitchen_body_sensor'].Occupancy }}
    {% else %}
      {{ states(entity_id) }}
    {% endif %}
