- platform: "mqtt"
  name: "body_sensor_occupancy_2"
  state_topic: "zigbee/tele/SENSOR"
  payload_on: "1"
  payload_off: "0"
  value_template: >
    {% if value_json.ZigbeeReceived['0xF5B2'] is defined %}
      {{ value_json.ZigbeeReceived['0xF5B2'].Occupancy }}
    {% else %}
      {{ states('sensor.body_sensor_occupancy_2') }}
    {% endif %}
